# Generated by Django 4.1.7 on 2023-05-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_vendas', models.CharField(max_length=11, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=9, null=True)),
                ('maquina', models.CharField(max_length=11, null=True)),
                ('status', models.CharField(max_length=30)),
                ('ultima_venda', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_vendas', models.CharField(max_length=11, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=9, null=True)),
                ('maquina', models.CharField(max_length=11, null=True)),
                ('status', models.CharField(max_length=30)),
                ('ultima_venda', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
